#!/bin/sh
# FILE NAME: app-config

set -e

# Customization Section
# Use this section to modify configuration files or execute preparation commands
# before the container starts. You can add any custom logic here.
# Refer to the /entrypoint script for additional details before making changes.

# Launch the application with the provided arguments
exec $@
