networks:
  proxy:

services:
  squid:
    image: squid-ssl-proxy:local
    networks:
      - proxy
    environment:
      - CERT_CN=squid.local
      - CERT_ORG=squid
      - CERT_OU=squid
      - CERT_COUNTRY=US
      - SQUID_PROXY_PORT=${SQUID_PROXY_PORT}
      - SQUID_PROXY_SSLBUMP_PORT=${SQUID_PROXY_SSLBUMP_PORT}
    ports:
      - "${SQUID_PROXY_PORT}:${SQUID_PROXY_PORT}"
      - "${SQUID_PROXY_SSLBUMP_PORT}:${SQUID_PROXY_SSLBUMP_PORT}"
    dns:
      - ${DNS_SERVER}
    volumes:
      - ./data/log:/var/log/
      - ./data/cache:/var/cache
      - ./data/cert:/etc/squid-cert
    restart: always
